// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace vaner29.VisualStudio.StupidVSPlugin
{
    internal sealed partial class Vsix
    {
        public const string Id = "cb63fe1e-356e-426d-abdf-9237436faf11";
        public const string Name = "Stupid VS Plugin";
        public const string Description = @"Stupid VS Plugin is a dumb extension that adds silly sounds to yout stupid IDE";
        public const string Language = "en-US";
        public const string Version = "0.1.0";
        public const string Author = "vaner29";
        public const string Tags = "sound events music effect build";
    }
}
